### PR TITLE
Add location permission feature

### PR DESCRIPTION
**Pull request by RachnaShriwas**
In WelcomeActivity screen user is requested to give location permission and in MainActivity the user's location(latitude and longitude) is displayed in a toast. This location can be used further by MainActivity.

### CODE REVIEW

**Comment by yhdesai** [comment]
YOu seem to also have commited files which are not supposed to be commited like  .gradle, .idea, build and the local.properties

**Comment by SaurabhSandav** [comment]
@yhdesai They should've been added to gitignore and never been committed in the first place. I'll add a proper gitignore and remove the unnecessary files later.

**Comment by yhdesai** [comment]
@SaurabhSandav We do have a .gitignore

**Comment by SaurabhSandav** [comment]
@yhdesai My bad, the last time I took a look at the repo was before the gitignore was updated. In any case there's still the .idea folder which should be removed.

**Comment by yhdesai** [comment]
@SaurabhSandav  Removed it

**Comment by harikautilya** [comment]
Closing due to latest base branch implementation sorry for the trouble. Please pull from latest tonight and start contributing

**Pull request closed without merging**
