### PR TITLE
Fix #47 - User details fragment layout

### LINKED ISSUE #47: User details Fragment
**Summary:**

Design Ui and behaviour

**Expected behaviour:**

Design according to mock-ups

**Screenshots:**

if needed

### PR DESCRIPTION
**Pull request by vishalrao8**
### Description
I have designed user detail and RecyclerView's item layout with some custom modifications to make it look more materialized. I have modified-

- Resource files containing appropriate values used by Views through out the layout.
- layout-v21 files to provide native support for elevated Views on and above API level 21.
- "ids.xml" file adding id for RecyclerView used to show places contributed by user.
- "build.gradle" file containing dependencies required for this change.

Dependencies required for this change are-
    
- com.android.support:cardview-v7:27.1.1
- com.android.support:recyclerview-v7:27.1.1
- de.hdodenhof:circleimageview:2.2.0

Fixes #47

### Type of Change:

- User Interface

### How Has This Been Tested?
I have tested this on a real device. Do have a look at attached view of designed layout from AS's layout editor.

screenshot 48
screenshot 49

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

### CODE REVIEW

**Comment by vishalrao8** [comment]
@geekanamika Removed

**Comment by harikautilya** [comment]
@vishalrao8 may i know the progress?

**Comment by vishalrao8** [comment]
@harikautilya Stuck at squashing.

**Comment by harikautilya** [comment]
@vishalrao8 ping me on slack

**Pull request merged**
