### PR TITLE
Home

### PR DESCRIPTION
**Pull request by Devesh1396**
Issue no #46 

Fixed: - Camel case naming convention as asked.

### CODE REVIEW

**Comment by harikautilya** [comment]
@Devesh1396 we have already included all your prev changes and  reformated it.
@Aaklii abort this PR

**Comment by Rondaul** [comment]
its a duplicate PR. So, we have closed it. Try to work on new issues.

**Comment by Devesh1396** [comment]
Yeah, I was asked to work on changes else I won't have sent PR again. Ask with Vivek. No point of sending duplicate PR. I've only worked on this issue before @Rondaul

**Comment by vvkvivekl** [comment]
@Devesh1396 no issues.. we fixed by own too (short in time).. so marked it as duplicate. to avoid confusion.. not to worry..

**Pull request closed without merging**
