### PR TITLE
Feature place fragment ui

### PR DESCRIPTION
**Pull request by GauravR31**
### Description
Designed the layout for the Add Place fragment in accordance with the provided mockup.

Fixes # 45

### Type of Change:
- User Interface

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Rondaul** [comment]
@GauravR31 use add place ids which i have already created and change the spacing and alignment in `ids.xml`. I have done that for a reason.

**Comment by theshivamlko** [comment]
@GauravR31 

1. Why commented `+//apply plugin: 'com.google.gms.google-services'`
2. Put shape color in color.xml
3. some ids not mentioned in ids.xml

**Comment by GauravR31** [comment]
@Rondaul when I first cloned the project the ids.xml file had only one id item, hence I created my own ids. I'll make the necessary changes now.

@theshivamlko 

1. I was getting an AAPT2 error related to google-services.json, therefore I commented that line so that the project could be built. I forgot to remove the comment and I'll do that now.
2. I'll do the same now.
3. I was only asked to add those ids which would be used in Java code.

**Comment by harikautilya** [comment]
@GauravR31 resolve Conflicts please

**Comment by GauravR31** [comment]
@harikautilya on it. Just give me 10 minutes.

**Comment by GauravR31** [comment]
@geekanamika Yeah I was having some trouble resolving conflicts hence the large number of commits. I'll try to squash them.

**Comment by GauravR31** [comment]
@geekanamika I'm unable to squash the commits. Should I just create a new PR? Sorry but I'm new to GitHub.

**Pull request closed without merging**
