### PR TITLE
Added Navigation Bar

### PR DESCRIPTION
**Pull request by tavishjain**
Completed issue #22 . Added the Navigation Bar . More items can be added as required . @geekanamika @SaurabhSandav @Bloody-Badboy please review it

### CODE REVIEW

**Comment by Rondaul** [comment]
can you post the screen shot of how the design looks too.

**Comment by tavishjain** [comment]
screenshot_2018-04-16-13-59-52-357_com udacity exploreindia

@Rondaul here is the screenshot

**Comment by tavishjain** [comment]
More items in the nav bar can be added as per requirement.

**Comment by geekanamika** [comment]
@tavishjain SS looks good, will get back to you asap. Thank you, keep contributing.

**Comment by Rondaul** [comment]
@tavishjain yup, will work for now. :)

**Comment by tavishjain** [comment]
whatsapp image 2018-04-17 at 9 36 42 pm
Updated the gradient with an image . Please see again  . Also need someone to help color he icons in the nav bar

**Comment by Rondaul** [comment]
Its good but I think the image can be better.

**Comment by tavishjain** [comment]
@Rondaul tried many images, but found this to fit the best

**Comment by vvkvivekl** [comment]
Hy gys.. can we keep Nav drawer on hold for now.. as we know we don't have that much categorizes to use in Nav drawer.. so we can think of bottom fixed nav.. Hold on.. we dont want you to be disappointed..

**Comment by Rondaul** [comment]
@vvkvivekl hmm.. as you seem fit. 👍

**Comment by harikautilya** [comment]
UI changed
Closing due to latest base branch implementation sorry for the trouble. Please pull from latest tonight and start contributing

**Pull request closed without merging**
