### PR TITLE
Fix #51 - Place Details Screen

### LINKED ISSUE #51: Place Details Screen
**Summary:**

Design Add Place Details Screen.

**Expected behaviour:**

Follow the mockup provided.

**Device and Android version:**
N/A

11 place detail

### PR DESCRIPTION
**Pull request by kamalshree**
### Description
Implemented the PlaceDetails Screen as per the mockup.

Fixes # [51]

### Type of Change:
**Delete irrelevant options.**

- Created the slider Image on the page.
- Implemented the sub Toolbar
- Also implemented the Text Slider.

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

placedetails

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
N/A

### Checklist:
**Delete irrelevant options.**

- My PR follows the style guidelines of this project
- I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- My changes generate no new warnings 
-  Tested locally both Landscape and Portrait mode and it works fine.

### CODE REVIEW

**Comment by harikautilya** [comment]
@kamalshree Can you implement the Same in MVP and update the PR

**Comment by geekanamika** [comment]
@kamalshree Adding to the kautilya's statement, Please make sure that there're no merge conflicts.

**Comment by harikautilya** [comment]
@kamalshree since it's high time and there is a duplicate PR as well ...we will abort this PR

Duplicate : https://github.com/UdacityAndroidDevScholarship/explore-india/pull/61

**Comment by kamalshree** [comment]
Indeed , Thanks

**Comment by vvkvivekl** [comment]
duplicate

**Pull request closed without merging**
